name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ enhanced ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout base
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker login
        env:
          ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        run: |
          echo "${ALIYUN_DOCKER_PASSWORD}" | docker login --username "${ALIYUN_DOCKER_USERNAME}" registry.cn-hangzhou.aliyuncs.com --password-stdin
      - name: Docker build image and push on master branch
        run: |
          docker buildx build --output "type=image,push=true" --platform=linux/amd64,linux/arm/v7,linux/arm64/v8 --tag registry.cn-hangzhou.aliyuncs.com/dianhsu/unblock-netease-music:latest .
          
